# این یک گردش کار اساسی برای کمک به شما در شروع کار است

نام: CI

# کنترل زمان گردش کار
بر:
  # گردش کار را در رویدادهای درخواست فشار یا کشش شروع می کند اما فقط برای شعبه "اصلی
  فشار دادن:
    شعب: [ "اصلی" ]
  pull_quest:
    شعب: [ "اصلی" ]

  # به شما امکان می دهد این گردش کار را به صورت دستی از برگه Actions اجرا کنید
  workflow_dispatch:

# یک گردش کار از یک یا چند شغل تشکیل شده است که می توانند به صورت متوالی یا موازی اجرا شوند
شغل ها:
  # این گردش کار شامل یک کار واحد به نام "ساخت" است"
  ساخت:
    # نوع دونده ای که کار در آن انجام خواهد شد
    اجرا می شود: ubuntu-Latest

    # مراحل نشان دهنده دنباله ای از کارهایی است که به عنوان بخشی از کار اجرا می شود
    مراحل:
      # مخزن خود را در زیر $ GITHUB_WORKSPACE بررسی کنید ، بنابراین شغل شما می تواند به آن دسترسی پیدا کند
      - استفاده می کند: اقدامات / checkout @ v3

      # با استفاده از پوسته دونده ها یک دستور واحد را اجرا می کند
      - نام: یک اسکریپت یک خط را اجرا کنید
        run: echo سلام ، جهان!

      # مجموعه ای از دستورات را با استفاده از پوسته دونده اجرا می کند
      - نام: یک اسکریپت چند خط را اجرا کنید
        اجرا: |
          echo اقدامات دیگری را برای ساختن اضافه کنید,
          تست اکو ، و پروژه خود را مستقر کنید.
